spring:
  datasource:
    # Jdbc è il protocollo, maria db è il driver che andremo a utilizzare. (vedi il pom)
    url: jdbc:mariadb://localhost:3306/vino
    username: vino
    password: vino
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      # Se lo schema cambia, mantiene tutti i dati, e imposta quelli nuovi sul default. Se usiamo create
      # cancella e crea tutto da zero. Questo eliminerà tutti i dati!
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    database: mysql